name: shop_conrol_panel
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

 


  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.5.4
  get: ^4.6.5
  get_storage: ^2.0.3
  collapsible_sidebar: ^2.0.2
  side_navigation: ^1.0.2
  desktop_drop: ^0.3.3
  drag_and_drop_windows: ^0.0.2
  dropdown_button2: ^1.7.2
  pluto_grid: ^5.0.5
  http: ^0.13.5
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

